Решение task_3.1.3
JDBC-Hibernate/Task_3.1.3 pull request #1
Opened 2024-02-19 13:49 UTC by Robisho

2024-02-19 19:12 UTC, pdasilem requested changes

2024-02-19 19:12 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controllers/RESTController.java
> +@RequestMapping("/api")
для админа и юзера отдельные контроллеры

2024-02-19 19:12 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/configs/WebSecurityConfig.java
>                  .antMatchers("/admin/**").hasRole("ADMIN")
где доступ к ресту?

2024-02-19 19:12 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controllers/RESTController.java
> +    public List<User> getAllUsers() {
это не рест контроллеры

2024-02-20 14:13 UTC, pdasilem requested changes

2024-02-20 14:13 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controllers/AdminRESTController.java
> +@RequestMapping("/api/admin/users")
оверсложно...
апи/админ
и апи/юзер на юзера

2024-02-20 15:28 UTC, Robisho commented on src/main/java/ru/itmentor/spring/boot_security/demo/controllers/UserRESTController.java
> +    public User getUserById(@PathVariable Long id) {
нужно обязательно ResponseEntity возвращать?

2024-02-21 11:40 UTC, pdasilem requested changes

2024-02-21 11:40 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controllers/UserRESTController.java
> +        UserDetails authUser = (UserDetails) SecurityContextHolder
это проверка точно лишняя. Зачем она тебе здесь? У тебя же метод конфигуре переопределен

2024-02-21 12:23 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/controllers/UserRESTController.java
> +    public User getUserById(@PathVariable Long id) {
в рест контроллере да

2024-02-21 12:23 UTC, pdasilem approved these changes

2024-02-21 12:36 UTC, merged